version: '3'

services:
  web:
    build: .
    command: >
       bash -c "
        cd /app/web 
        python manage.py runserver 0.0.0.0:8000 --settings=shopping.settings
        "
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT:-9000}:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=shopping.settings
      # - DATABASE_URL=postgres://user:pass@postgres:5432/db
      - SECRET_KEY=mysecretkey
      - POSTGRES_HOST=${DB_HOST:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-1234}
      - POSTGRES_DB=${DB_NAME:-shopping}
      - POSTGRES_PORT=${DB_PORT:-5432}
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: ${DB_NAME:-shopping}
      PGDATA: /data/postgres
    volumes:
      - shopping_postgres_data:/var/lib/postgresql/data/
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
        - shopping_pgadmin:/root/.pgadmin
        - ./db:/tmp
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
        - postgres 

volumes:
  shopping_postgres_data:
  shopping_pgadmin:
